# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to=utils.get_file_path),
        ),
    ]
