# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170411_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(height_field=16, upload_to='/static/img/favicon.png', width_field=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
        ),
    ]
