# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170412_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteglobalconfig',
            name='favicon',
            field=models.ImageField(upload_to='icons'),
        ),
    ]
