# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='body',
            field=models.TextField(),
        ),
    ]
